/**
 * Helper code generators (header, utility functions)
 */

import type { ModelFeatures } from "./features.js"

export function generateHeader(modelName: string): string {
  return `//
//  ${modelName}Generated.swift
//  NodeMLXCore
//
//  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
//  Generated by hf2swift from model patterns.
//  Re-run the generator to update this file.
//
//  Based on patterns from mlx-lm and mlx-swift-lm.
//

import Foundation
import MLX
import MLXFast
import MLXNN`
}

export function generateHelpers(features: ModelFeatures): string {
  const parts: string[] = ["// MARK: - Utility Functions"]

  // clipResidual helper for float16 overflow protection
  if (features.useClipResidual) {
    parts.push(`
/// Clip residual for float16 overflow protection (matching mlx-lm)
private func clipResidual(_ x: MLXArray, _ y: MLXArray) -> MLXArray {
    if x.dtype != .float16 {
        return x + y
    }
    let bound = Float16.greatestFiniteMagnitude
    let sum = (x.asType(.float32) + y.asType(.float32))
    return clip(sum, min: MLXArray(-Float(bound)), max: MLXArray(Float(bound))).asType(.float16)
}`)
  }

  return parts.join("\n")
}
