/**
 * Helper code generators (header, utility functions, advanced components)
 */

import type { ModelFeatures } from "./features.js"

export function generateHeader(modelName: string): string {
  return `//
//  ${modelName}Generated.swift
//  NodeMLXCore
//
//  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
//  Generated by hf2swift from model patterns.
//  Re-run the generator to update this file.
//
//  Based on patterns from mlx-lm and mlx-swift-lm.
//

import Foundation
import MLX
import MLXFast
import MLXNN`
}

export function generateHelpers(features: ModelFeatures): string {
  const parts: string[] = ["// MARK: - Utility Functions"]

  // clipResidual helper - use shared MathUtils
  if (features.useClipResidual) {
    parts.push(`
/// Clip residual for float16 overflow protection - uses shared implementation
private func clipResidual(_ x: MLXArray, _ y: MLXArray) -> MLXArray {
    MathUtils.clipResidual(x, y)
}`)
  }

  // mlxTopK helper - use shared MathUtils
  if (features.hasMoE) {
    parts.push(`
/// Top-k selection for MoE routing - uses shared implementation
private func mlxTopK(_ a: MLXArray, k: Int, axis: Int = -1) -> (values: MLXArray, indices: MLXArray) {
    MathUtils.topK(a, k: k, axis: axis)
}`)
  }

  return parts.join("\n")
}

/**
 * Generate Laurel (Learned Augmented Residual) block
 * Uses shared LaurelBlock<C> component.
 */
export function generateLaurelBlock(modelName: string, configClass: string): string {
  return `// MARK: - Laurel Block

/// LaurelConfiguration conformance for shared LaurelBlock
extension ${configClass}: LaurelConfiguration {}

/// Laurel block - uses shared implementation
typealias ${modelName}LaurelBlock = LaurelBlock<${configClass}>
`
}

/**
 * Generate AltUp (Alternating Updates) block
 * Uses shared AltUpBlock<C> component.
 */
export function generateAltUpBlock(modelName: string, configClass: string): string {
  return `// MARK: - AltUp Block

/// AltUpConfiguration conformance for shared AltUpBlock
extension ${configClass}: AltUpConfiguration {}

/// AltUp block - uses shared implementation
typealias ${modelName}AltUp = AltUpBlock<${configClass}>
`
}
