import { describe, it, expect } from "vitest"
import { SwiftGenerator } from "./index.js"

describe("SwiftGenerator", () => {
  describe("generate", () => {
    it("generates file header", () => {
      const generator = new SwiftGenerator("qwen2")
      const result = generator.generate([])

      expect(result).toContain("//  Qwen2.swift")
      expect(result).toContain("auto-generated by hf2swift")
      expect(result).toContain("import Foundation")
      expect(result).toContain("import MLX")
      expect(result).toContain("import MLXFast")
      expect(result).toContain("import MLXNN")
    })

    it("generates RMSNorm for standard models", () => {
      const generator = new SwiftGenerator("qwen2")
      const result = generator.generate([])

      expect(result).toContain("class Qwen2RMSNorm: Module")
      expect(result).toContain("MLXFast.rmsNorm(x, weight: weight, eps: eps)")
    })

    it("generates Gemma-style RMSNorm for gemma3", () => {
      const generator = new SwiftGenerator("gemma3")
      const result = generator.generate([])

      expect(result).toContain("class Gemma3RMSNorm: Module")
      expect(result).toContain("1 + weight")
      expect(result).toContain("MLXFast.rmsNorm(x, weight: 1 + weight, eps: eps)")
    })

    it("generates clipResidual for gemma3", () => {
      const generator = new SwiftGenerator("gemma3")
      const result = generator.generate([])

      expect(result).toContain("func clipResidual")
      expect(result).toContain("Float16.greatestFiniteMagnitude")
    })

    it("does not generate clipResidual for qwen", () => {
      const generator = new SwiftGenerator("qwen2")
      const result = generator.generate([])

      expect(result).not.toContain("func clipResidual")
    })

    it("generates MLP with geluApproximate for gemma3", () => {
      const generator = new SwiftGenerator("gemma3")
      const result = generator.generate([])

      expect(result).toContain("class Gemma3MLP: Module")
      expect(result).toContain("geluApproximate(gateProj(x))")
    })

    it("generates MLP with silu for qwen", () => {
      const generator = new SwiftGenerator("qwen2")
      const result = generator.generate([])

      expect(result).toContain("class Qwen2MLP: Module")
      expect(result).toContain("silu(gateProj(x))")
    })

    it("generates Attention with Q/K norms for gemma3", () => {
      const generator = new SwiftGenerator("gemma3")
      const result = generator.generate([])

      expect(result).toContain("class Gemma3Attention: Module")
      expect(result).toContain("qNorm: Gemma3RMSNorm")
      expect(result).toContain("kNorm: Gemma3RMSNorm")
      expect(result).toContain("queries = qNorm(queries)")
    })

    it("generates Attention without Q/K norms for qwen", () => {
      const generator = new SwiftGenerator("qwen2")
      const result = generator.generate([])

      expect(result).toContain("class Qwen2Attention: Module")
      expect(result).not.toContain("qNorm: Qwen2RMSNorm")
    })

    it("generates sliding window for gemma3", () => {
      const generator = new SwiftGenerator("gemma3")
      const result = generator.generate([])

      expect(result).toContain("let rope: any RoPEProvider")
      expect(result).toContain("isGlobalLayer(layerIdx)")
      expect(result).toContain("RotatingKVCache")
      expect(result).toContain("slidingWindowPattern")
    })

    it("generates 4 norms per layer for gemma3", () => {
      const generator = new SwiftGenerator("gemma3")
      const result = generator.generate([])

      expect(result).toContain("preFeedforwardLayernorm")
      expect(result).toContain("postFeedforwardLayernorm")
    })

    it("generates 2 norms per layer for qwen", () => {
      const generator = new SwiftGenerator("qwen2")
      const result = generator.generate([])

      expect(result).not.toContain("preFeedforwardLayernorm")
    })

    it("generates model with cache support", () => {
      const generator = new SwiftGenerator("qwen2")
      const result = generator.generate([])

      expect(result).toContain("public class Qwen2Model: Module, LLMModel")
      expect(result).toContain("public var supportsCache: Bool { true }")
      expect(result).toContain("public func newCache()")
      expect(result).toContain("cache: inout [KVCache]?")
    })

    it("generates sanitize function", () => {
      const generator = new SwiftGenerator("test")
      const result = generator.generate([])

      expect(result).toContain("public func sanitize(weights:")
      expect(result).toContain("language_model.model.")
      expect(result).toContain("vision_tower")
    })
  })
})
