//
//  Llama.swift
//  Auto-generated by hf2swift v5
//
//  This file was generated from HuggingFace Transformers source code.
//  The structure follows patterns from mlx-swift-lm (MIT License, ml-explore).
//  See: https://github.com/ml-explore/mlx-swift-lm
//

import Foundation
import MLX
import MLXFast
import MLXNN

// Note: KVCache and LLMModel protocols are defined in NodeMLXCore
// Import them if using this as a standalone file

// MARK: - Configuration

public struct LlamaConfiguration: Codable, Sendable {
    public var attentionBias: Bool
    public let attentionDropout: Float?
    public var bosTokenId: Int
    public let eosTokenId: [Int]
    public var headDim: Int
    public var hiddenAct: String
    public var hiddenSize: Int
    public let initializerRange: Float?
    public var intermediateSize: Int
    public var maxPositionEmbeddings: Int
    public let mlpBias: Bool?
    public var modelType: String
    public var numAttentionHeads: Int
    public var numHiddenLayers: Int
    public var numKeyValueHeads: Int
    public let pretrainingTp: Int?
    public var rmsNormEps: Float
    public var ropeTheta: Float
    public var tieWordEmbeddings: Bool
    public let useCache: Bool?
    public var vocabSize: Int

    enum CodingKeys: String, CodingKey {
        case attentionBias = "attention_bias"
        case attentionDropout = "attention_dropout"
        case bosTokenId = "bos_token_id"
        case eosTokenId = "eos_token_id"
        case headDim = "head_dim"
        case hiddenAct = "hidden_act"
        case hiddenSize = "hidden_size"
        case initializerRange = "initializer_range"
        case intermediateSize = "intermediate_size"
        case maxPositionEmbeddings = "max_position_embeddings"
        case mlpBias = "mlp_bias"
        case modelType = "model_type"
        case numAttentionHeads = "num_attention_heads"
        case numHiddenLayers = "num_hidden_layers"
        case numKeyValueHeads = "num_key_value_heads"
        case pretrainingTp = "pretraining_tp"
        case rmsNormEps = "rms_norm_eps"
        case ropeTheta = "rope_theta"
        case tieWordEmbeddings = "tie_word_embeddings"
        case useCache = "use_cache"
        case vocabSize = "vocab_size"
    }

}

// MARK: - Helper Functions

/// Apply rotary position embeddings for Llama
private func llamaApplyRotaryPosEmb(
    _ q: MLXArray,
    _ k: MLXArray,
    cos: MLXArray,
    sin: MLXArray
) -> (MLXArray, MLXArray) {
    let qEmbed = (q * cos) + (llamaRotateHalf(q) * sin)
    let kEmbed = (k * cos) + (llamaRotateHalf(k) * sin)
    return (qEmbed, kEmbed)
}

/// Rotate half of the tensor for Llama
private func llamaRotateHalf(_ x: MLXArray) -> MLXArray {
    let halfDim = x.dim(-1) / 2
    let x1 = x[.ellipsis, ..<halfDim]
    let x2 = x[.ellipsis, halfDim...]
    return concatenated([-x2, x1], axis: -1)
}

// MARK: - Model Components

// MARK: - LlamaAttention

class LlamaAttention: Module {
    @ModuleInfo(key: "q_proj") var qProj: Linear
    @ModuleInfo(key: "k_proj") var kProj: Linear
    @ModuleInfo(key: "v_proj") var vProj: Linear
    @ModuleInfo(key: "o_proj") var oProj: Linear

    let numHeads: Int
    let numKVHeads: Int
    let headDim: Int
    let scale: Float

    init(_ config: LlamaConfiguration) {
        let hiddenSize = config.hiddenSize
        self.numHeads = config.numAttentionHeads
        self.numKVHeads = config.numKeyValueHeads ?? config.numAttentionHeads
        self.headDim = config.headDim
        self.scale = 1.0 / sqrt(Float(headDim))

        self._qProj.wrappedValue = Linear(hiddenSize, numHeads * headDim, bias: config.attentionBias ?? false)
        self._kProj.wrappedValue = Linear(hiddenSize, numKVHeads * headDim, bias: config.attentionBias ?? false)
        self._vProj.wrappedValue = Linear(hiddenSize, numKVHeads * headDim, bias: config.attentionBias ?? false)
        self._oProj.wrappedValue = Linear(numHeads * headDim, hiddenSize, bias: config.attentionBias ?? false)
    }

    func callAsFunction(
        _ x: MLXArray,
        mask: MLXArray? = nil
    ) -> MLXArray {
        let (B, L, _) = (x.dim(0), x.dim(1), x.dim(2))

        var queries = qProj(x)
        var keys = kProj(x)
        var values = vProj(x)

        // Reshape: [B, L, H, D] -> [B, H, L, D]
        queries = queries.reshaped([B, L, numHeads, headDim]).transposed(0, 2, 1, 3)
        keys = keys.reshaped([B, L, numKVHeads, headDim]).transposed(0, 2, 1, 3)
        values = values.reshaped([B, L, numKVHeads, headDim]).transposed(0, 2, 1, 3)

        // Repeat KV heads if needed (GQA)
        if numKVHeads < numHeads {
            let repeats = numHeads / numKVHeads
            keys = MLXArray.repeated(keys, count: repeats, axis: 1)
            values = MLXArray.repeated(values, count: repeats, axis: 1)
        }

        // Scaled dot-product attention
        var attnWeights = matmul(queries, keys.transposed(0, 1, 3, 2)) * scale

        if let mask = mask {
            attnWeights = attnWeights + mask
        }

        attnWeights = softmax(attnWeights, axis: -1)
        let output = matmul(attnWeights, values)

        // Reshape back: [B, H, L, D] -> [B, L, H*D]
        let outputReshaped = output.transposed(0, 2, 1, 3).reshaped([B, L, numHeads * headDim])

        return oProj(outputReshaped)
    }
}

// MARK: - LlamaMLP

class LlamaMLP: Module {
    @ModuleInfo(key: "gate_proj") var gateProj: Linear
    @ModuleInfo(key: "up_proj") var upProj: Linear
    @ModuleInfo(key: "down_proj") var downProj: Linear

    init(_ config: LlamaConfiguration) {
        let hiddenSize = config.hiddenSize
        let intermediateSize = config.intermediateSize
        self._gateProj.wrappedValue = Linear(hiddenSize, intermediateSize, bias: false)
        self._upProj.wrappedValue = Linear(hiddenSize, intermediateSize, bias: false)
        self._downProj.wrappedValue = Linear(intermediateSize, hiddenSize, bias: false)
    }

    func callAsFunction(_ x: MLXArray) -> MLXArray {
        return downProj(silu(gateProj(x)) * upProj(x))
    }
}

// MARK: - LlamaRMSNorm (using built-in RMSNorm)

// Note: Using MLXNN.RMSNorm directly

// MARK: - LlamaTransformerBlock

class LlamaTransformerBlock: Module {
    @ModuleInfo(key: "self_attn") var attention: LlamaAttention
    let mlp: LlamaMLP
    @ModuleInfo(key: "input_layernorm") var inputLayerNorm: RMSNorm
    @ModuleInfo(key: "post_attention_layernorm") var postAttentionLayerNorm: RMSNorm

    init(_ config: LlamaConfiguration) {
        self._attention.wrappedValue = LlamaAttention(config)
        self.mlp = LlamaMLP(config)
        self._inputLayerNorm.wrappedValue = RMSNorm(
            dimensions: config.hiddenSize, eps: config.rmsNormEps ?? 1e-6)
        self._postAttentionLayerNorm.wrappedValue = RMSNorm(
            dimensions: config.hiddenSize, eps: config.rmsNormEps ?? 1e-6)
    }

    func callAsFunction(
        _ x: MLXArray,
        mask: MLXArray? = nil
    ) -> MLXArray {
        // Self-attention with residual
        let residual1 = x
        let h1 = inputLayerNorm(x)
        let attnOut = attention(h1, mask: mask)
        let h2 = residual1 + attnOut

        // MLP with residual
        let residual2 = h2
        let h3 = postAttentionLayerNorm(h2)
        let mlpOut = mlp(h3)
        return residual2 + mlpOut
    }
}

// MARK: - LlamaModelInner

public class LlamaModelInner: Module {
    @ModuleInfo(key: "embed_tokens") var embedTokens: Embedding
    let layers: [LlamaTransformerBlock]
    @ModuleInfo(key: "norm") var norm: RMSNorm

    public init(_ config: LlamaConfiguration) {
        self._embedTokens.wrappedValue = Embedding(
            embeddingCount: config.vocabSize,
            dimensions: config.hiddenSize
        )
        self.layers = (0..<config.numHiddenLayers).map { _ in
            LlamaTransformerBlock(config)
        }
        self._norm.wrappedValue = RMSNorm(
            dimensions: config.hiddenSize, eps: config.rmsNormEps ?? 1e-6)
    }

    public func callAsFunction(_ inputIds: MLXArray) -> MLXArray {
        var h = embedTokens(inputIds)

        for layer in layers {
            h = layer(h, mask: nil)
        }

        return norm(h)
    }
}

// MARK: - LlamaModel

public class LlamaModel: Module {
    public let vocabularySize: Int
    public let numLayers: Int
    public let numKVHeads: Int

    public let model: LlamaModelInner
    @ModuleInfo(key: "lm_head") var lmHead: Linear
    private let config: LlamaConfiguration

    public init(_ config: LlamaConfiguration) {
        self.config = config
        self.vocabularySize = config.vocabSize
        self.numLayers = config.numHiddenLayers
        self.numKVHeads = config.numKeyValueHeads ?? config.numAttentionHeads
        self.model = LlamaModelInner(config)
        self._lmHead.wrappedValue = Linear(config.hiddenSize, config.vocabSize, bias: false)
    }

    /// Embed input tokens
    public func embed(_ inputIds: MLXArray) -> MLXArray {
        return model.embedTokens(inputIds)
    }

    /// Forward pass: compute logits from input token IDs
    public func callAsFunction(_ inputIds: MLXArray) -> MLXArray {
        let h = model(inputIds)
        return lmHead(h)
    }

    /// Sanitize weight keys during model loading
    public func sanitize(weights: [String: MLXArray]) -> [String: MLXArray] {
        // Override in subclass if weight key mapping needed
        return weights
    }
}