//
//  Gemma3.swift
//  NodeMLXCore
//
//  Gemma3 Model implementation (auto-generated by hf2swift).
//  Based on patterns from mlx-lm and mlx-swift-lm.
//

import Foundation
import MLX
import MLXFast
import MLXNN

// MARK: - Configuration

public struct Gemma3Configuration: Decodable, Sendable {
    public var hiddenSize: Int
    public var numHiddenLayers: Int
    public var numAttentionHeads: Int
    public var numKeyValueHeads: Int
    public var intermediateSize: Int
    public var vocabSize: Int
    public var headDim: Int
    public var rmsNormEps: Float
    public var ropeTheta: Float
    public var maxPositionEmbeddings: Int
    public var slidingWindow: Int
    public var slidingWindowPattern: Int
    public var ropeLocalTheta: Float
    public var ropeScaling: [String: StringOrNumber]?

    /// Check if a layer is a global attention layer
    public func isGlobalLayer(_ layerIdx: Int) -> Bool {
        return (layerIdx % slidingWindowPattern) == (slidingWindowPattern - 1)
    }

    enum CodingKeys: String, CodingKey {
        case textConfig = "text_config"
        case hiddenSize = "hidden_size"
        case numHiddenLayers = "num_hidden_layers"
        case numAttentionHeads = "num_attention_heads"
        case numKeyValueHeads = "num_key_value_heads"
        case intermediateSize = "intermediate_size"
        case vocabSize = "vocab_size"
        case headDim = "head_dim"
        case rmsNormEps = "rms_norm_eps"
        case ropeTheta = "rope_theta"
        case maxPositionEmbeddings = "max_position_embeddings"
        case slidingWindow = "sliding_window"
        case slidingWindowPattern = "sliding_window_pattern"
        case ropeLocalTheta = "rope_local_base_freq"
        case ropeScaling = "rope_scaling"
    }

    public init(from decoder: Swift.Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        // Helper to decode from text_config or top level
        func decode<T: Decodable>(_ key: CodingKeys, default defaultValue: T? = nil) throws -> T {
            if let nested = try? container.nestedContainer(keyedBy: CodingKeys.self, forKey: .textConfig),
               let value = try? nested.decode(T.self, forKey: key)
            {
                return value
            }
            if let value = try? container.decode(T.self, forKey: key) {
                return value
            }
            if let defaultValue = defaultValue {
                return defaultValue
            }
            throw DecodingError.keyNotFound(key, DecodingError.Context(codingPath: [], debugDescription: "Missing \(key)"))
        }

        hiddenSize = try decode(.hiddenSize)
        numHiddenLayers = try decode(.numHiddenLayers)
        numAttentionHeads = try decode(.numAttentionHeads)
        numKeyValueHeads = try decode(.numKeyValueHeads, default: numAttentionHeads)
        intermediateSize = try decode(.intermediateSize)
        vocabSize = try decode(.vocabSize)
        headDim = try decode(.headDim, default: hiddenSize / numAttentionHeads)
        rmsNormEps = try decode(.rmsNormEps, default: 1e-6)
        ropeTheta = try decode(.ropeTheta, default: 1_000_000.0)
        maxPositionEmbeddings = try decode(.maxPositionEmbeddings, default: 32768)
        slidingWindow = try decode(.slidingWindow, default: 512)
        slidingWindowPattern = try decode(.slidingWindowPattern, default: 6)
        ropeLocalTheta = try decode(.ropeLocalTheta, default: 10000.0)
        ropeScaling = try? container.decode([String: StringOrNumber].self, forKey: .ropeScaling)
    }
}

// MARK: - RMS Norm (Gemma style - uses 1+weight scaling)

class Gemma3RMSNorm: Module {
    let eps: Float

    @ModuleInfo(key: "weight") var weight: MLXArray

    init(dimensions: Int, eps: Float = 1e-6) {
        self.eps = eps
        // Initialize to zeros - will be (1 + weight) in forward
        _weight.wrappedValue = MLXArray.zeros([dimensions])
    }

    func callAsFunction(_ x: MLXArray) -> MLXArray {
        // Gemma uses (1 + weight) scaling
        return MLXFast.rmsNorm(x, weight: 1 + weight, eps: eps)
    }
}

// MARK: - Utility Functions

/// Clip residual for float16 overflow protection (matching mlx-lm)
private func clipResidual(_ x: MLXArray, _ y: MLXArray) -> MLXArray {
    if x.dtype != .float16 {
        return x + y
    }
    let bound = Float16.greatestFiniteMagnitude
    let sum = (x.asType(.float32) + y.asType(.float32))
    return clip(sum, min: MLXArray(-Float(bound)), max: MLXArray(Float(bound))).asType(.float16)
}

// MARK: - Attention

class Gemma3Attention: Module {
    @ModuleInfo(key: "q_proj") var qProj: Linear
    @ModuleInfo(key: "k_proj") var kProj: Linear
    @ModuleInfo(key: "v_proj") var vProj: Linear
    @ModuleInfo(key: "o_proj") var oProj: Linear
    @ModuleInfo(key: "q_norm") var qNorm: Gemma3RMSNorm
    @ModuleInfo(key: "k_norm") var kNorm: Gemma3RMSNorm

    let numHeads: Int
    let numKVHeads: Int
    let headDim: Int
    let scale: Float
    let rope: any RoPEProvider
    let isGlobal: Bool
    let slidingWindow: Int?

    init(_ config: Gemma3Configuration, layerIdx: Int) {
        numHeads = config.numAttentionHeads
        numKVHeads = config.numKeyValueHeads
        headDim = config.headDim
        scale = 1.0 / sqrt(Float(headDim))

        let qDim = numHeads * headDim
        let kvDim = numKVHeads * headDim

        _qProj.wrappedValue = Linear(config.hiddenSize, qDim, bias: false)
        _kProj.wrappedValue = Linear(config.hiddenSize, kvDim, bias: false)
        _vProj.wrappedValue = Linear(config.hiddenSize, kvDim, bias: false)
        _oProj.wrappedValue = Linear(qDim, config.hiddenSize, bias: false)

        _qNorm.wrappedValue = Gemma3RMSNorm(dimensions: headDim, eps: config.rmsNormEps)
        _kNorm.wrappedValue = Gemma3RMSNorm(dimensions: headDim, eps: config.rmsNormEps)

        isGlobal = config.isGlobalLayer(layerIdx)
        slidingWindow = isGlobal ? nil : config.slidingWindow

        // Different RoPE theta for sliding vs global layers
        let ropeBase = isGlobal ? config.ropeTheta : config.ropeLocalTheta

        // Use initializeRope to handle linear scaling for larger models
        rope = initializeRope(
            dims: headDim,
            base: ropeBase,
            traditional: false,
            scalingConfig: isGlobal ? config.ropeScaling : nil,
            maxPositionEmbeddings: config.maxPositionEmbeddings
        )
    }

    func callAsFunction(
        _ hiddenStates: MLXArray,
        mask: MLXFast.ScaledDotProductAttentionMaskMode,
        cache: inout KVCache?
    ) -> MLXArray {
        let (B, L, _) = (hiddenStates.dim(0), hiddenStates.dim(1), hiddenStates.dim(2))

        // Project to Q, K, V and reshape
        var queries = qProj(hiddenStates).reshaped([B, L, numHeads, headDim])
        var keys = kProj(hiddenStates).reshaped([B, L, numKVHeads, headDim])
        var values = vProj(hiddenStates).reshaped([B, L, numKVHeads, headDim])

        // Apply RMSNorm to Q and K
        queries = qNorm(queries)
        keys = kNorm(keys)

        // Transpose for attention: [B, heads, L, headDim]
        queries = queries.transposed(0, 2, 1, 3)
        keys = keys.transposed(0, 2, 1, 3)
        values = values.transposed(0, 2, 1, 3)

        // Apply RoPE with cache offset
        let offset = cache?.offset ?? 0
        queries = rope.apply(queries, offset: offset)
        keys = rope.apply(keys, offset: offset)

        // Update cache
        if let c = cache {
            (keys, values) = c.update(keys: keys, values: values)
        }

        // Attention using MLXFast (handles GQA automatically)
        let output = MLXFast.scaledDotProductAttention(
            queries: queries,
            keys: keys,
            values: values,
            scale: scale,
            mask: mask
        )

        // Reshape back: [B, heads, L, headDim] -> [B, L, hidden]
        let outputReshaped = output.transposed(0, 2, 1, 3).reshaped([B, L, -1])

        return oProj(outputReshaped)
    }
}

// MARK: - MLP

class Gemma3MLP: Module {
    @ModuleInfo(key: "gate_proj") var gateProj: Linear
    @ModuleInfo(key: "up_proj") var upProj: Linear
    @ModuleInfo(key: "down_proj") var downProj: Linear

    init(_ config: Gemma3Configuration) {
        _gateProj.wrappedValue = Linear(config.hiddenSize, config.intermediateSize, bias: false)
        _upProj.wrappedValue = Linear(config.hiddenSize, config.intermediateSize, bias: false)
        _downProj.wrappedValue = Linear(config.intermediateSize, config.hiddenSize, bias: false)
    }

    func callAsFunction(_ x: MLXArray) -> MLXArray {
        return downProj(geluApproximate(gateProj(x)) * upProj(x))
    }
}

// MARK: - Decoder Layer

class Gemma3DecoderLayer: Module {
    @ModuleInfo(key: "self_attn") var selfAttn: Gemma3Attention
    @ModuleInfo(key: "mlp") var mlp: Gemma3MLP
    @ModuleInfo(key: "input_layernorm") var inputLayernorm: Gemma3RMSNorm
    @ModuleInfo(key: "post_attention_layernorm") var postAttentionLayernorm: Gemma3RMSNorm
    @ModuleInfo(key: "pre_feedforward_layernorm") var preFeedforwardLayernorm: Gemma3RMSNorm
    @ModuleInfo(key: "post_feedforward_layernorm") var postFeedforwardLayernorm: Gemma3RMSNorm

    init(_ config: Gemma3Configuration, layerIdx: Int) {
        _selfAttn.wrappedValue = Gemma3Attention(config, layerIdx: layerIdx)
        _mlp.wrappedValue = Gemma3MLP(config)
        _inputLayernorm.wrappedValue = Gemma3RMSNorm(dimensions: config.hiddenSize, eps: config.rmsNormEps)
        _postAttentionLayernorm.wrappedValue = Gemma3RMSNorm(dimensions: config.hiddenSize, eps: config.rmsNormEps)
        _preFeedforwardLayernorm.wrappedValue = Gemma3RMSNorm(dimensions: config.hiddenSize, eps: config.rmsNormEps)
        _postFeedforwardLayernorm.wrappedValue = Gemma3RMSNorm(dimensions: config.hiddenSize, eps: config.rmsNormEps)
    }

    func callAsFunction(
        _ hiddenStates: MLXArray,
        mask: MLXFast.ScaledDotProductAttentionMaskMode,
        cache: inout KVCache?
    ) -> MLXArray {
        // 1. Pre-norm + Self-attention
        let normed = inputLayernorm(hiddenStates)
        let attnOut = selfAttn(normed, mask: mask, cache: &cache)
        let attnNormed = postAttentionLayernorm(attnOut)
        var h = clipResidual(hiddenStates, attnNormed)

        // 2. Pre-norm + MLP
        let mlpIn = preFeedforwardLayernorm(h)
        let mlpOut = mlp(mlpIn)
        let mlpNormed = postFeedforwardLayernorm(mlpOut)
        h = clipResidual(h, mlpNormed)

        return h
    }
}

// MARK: - Model Inner

class Gemma3ModelInner: Module {
    @ModuleInfo(key: "embed_tokens") var embedTokens: Embedding
    @ModuleInfo(key: "layers") var layers: [Gemma3DecoderLayer]
    @ModuleInfo(key: "norm") var norm: Gemma3RMSNorm

    let numLayers: Int
    let hiddenSize: Int
    let slidingWindow: Int
    let slidingWindowPattern: Int

    init(_ config: Gemma3Configuration) {
        numLayers = config.numHiddenLayers
        hiddenSize = config.hiddenSize
        slidingWindow = config.slidingWindow
        slidingWindowPattern = config.slidingWindowPattern
        _embedTokens.wrappedValue = Embedding(embeddingCount: config.vocabSize, dimensions: config.hiddenSize)
        _layers.wrappedValue = (0 ..< numLayers).map { idx in Gemma3DecoderLayer(config, layerIdx: idx) }
        _norm.wrappedValue = Gemma3RMSNorm(dimensions: config.hiddenSize, eps: config.rmsNormEps)
    }

    func callAsFunction(
        _ inputIds: MLXArray,
        cache: inout [KVCache?]
    ) -> MLXArray {
        // Get embeddings and scale by sqrt(hiddenSize) - Gemma specific
        var hiddenStates = embedTokens(inputIds)
        let scale = MLXArray(sqrt(Float(hiddenSize)))
        hiddenStates = hiddenStates * scale.asType(hiddenStates.dtype)

        // Create masks following mlx-lm pattern:
        // - Global mask: uses cache from a global layer (pattern - 1)
        // - Sliding mask: uses cache from first layer with sliding window size
        let globalLayerIdx = slidingWindowPattern - 1
        let globalCache = globalLayerIdx < cache.count ? cache[globalLayerIdx] : nil
        let globalMask = createAttentionMask(h: hiddenStates, cache: globalCache, windowSize: nil)

        // Sliding window mask (only if pattern > 1)
        let slidingMask: MLXFast.ScaledDotProductAttentionMaskMode
        if slidingWindowPattern > 1 {
            let firstCache = cache.first ?? nil
            slidingMask = createAttentionMask(h: hiddenStates, cache: firstCache, windowSize: slidingWindow)
        } else {
            slidingMask = globalMask
        }

        for i in 0 ..< layers.count {
            // Layer is global if i % pattern == pattern - 1 (matching mlx-lm)
            let isGlobal = (i % slidingWindowPattern) == (slidingWindowPattern - 1)
            let mask = isGlobal ? globalMask : slidingMask
            hiddenStates = layers[i](hiddenStates, mask: mask, cache: &cache[i])
        }

        return norm(hiddenStates)
    }
}

// MARK: - Top-Level Model

public class Gemma3Model: Module, LLMModel {
    public let vocabularySize: Int
    public let numLayers: Int
    public let numKVHeads: Int
    public let headDim: Int

    @ModuleInfo(key: "model") var model: Gemma3ModelInner
    @ModuleInfo(key: "lm_head") var lmHead: Linear

    private let config: Gemma3Configuration

    public var supportsCache: Bool { true }

    public init(_ config: Gemma3Configuration) {
        self.config = config
        vocabularySize = config.vocabSize
        numLayers = config.numHiddenLayers
        numKVHeads = config.numKeyValueHeads
        headDim = config.headDim

        _model.wrappedValue = Gemma3ModelInner(config)
        _lmHead.wrappedValue = Linear(config.hiddenSize, config.vocabSize, bias: false)
    }

    /// Forward pass without cache
    public func callAsFunction(_ inputIds: MLXArray) -> MLXArray {
        var cache: [KVCache?] = Array(repeating: nil, count: numLayers)
        let h = model(inputIds, cache: &cache)
        return lmHead(h)
    }

    /// Forward pass with KV cache for efficient generation
    public func callAsFunction(_ inputIds: MLXArray, cache: inout [KVCache]?) -> MLXArray {
        var layerCaches: [KVCache?]
        if let existingCache = cache {
            layerCaches = existingCache.map { $0 as KVCache? }
        } else {
            layerCaches = Array(repeating: nil, count: numLayers)
        }

        let h = model(inputIds, cache: &layerCaches)

        cache = layerCaches.compactMap { $0 }

        return lmHead(h)
    }

    /// Create a new KV cache with appropriate cache types per layer
    /// Following mlx-lm pattern: global layers use KVCacheSimple, others use RotatingKVCache
    public func newCache() -> [KVCache] {
        return (0 ..< numLayers).map { i in
            // Layer is global if i % pattern == pattern - 1
            let isGlobal = (i % config.slidingWindowPattern) == (config.slidingWindowPattern - 1)
            if isGlobal {
                return KVCacheSimple()
            } else {
                return RotatingKVCache(maxSize: config.slidingWindow, keep: 0)
            }
        }
    }

    /// Sanitize weight keys from HuggingFace format
    public func sanitize(weights: [String: MLXArray]) -> [String: MLXArray] {
        var result: [String: MLXArray] = [:]

        for (key, value) in weights {
            var newKey = key

            // VLM format transformations:
            // - language_model.model.X -> model.X (transformer layers)
            // - language_model.lm_head.X -> lm_head.X (output projection)
            // - language_model.X -> X (other components)
            if newKey.hasPrefix("language_model.model.") {
                newKey = "model." + String(newKey.dropFirst("language_model.model.".count))
            } else if newKey.hasPrefix("language_model.lm_head.") {
                newKey = "lm_head." + String(newKey.dropFirst("language_model.lm_head.".count))
            } else if newKey.hasPrefix("language_model.") {
                newKey = String(newKey.dropFirst("language_model.".count))
            }

            // Skip vision/audio tower weights
            if newKey.contains("vision_tower") || newKey.contains("audio_tower") ||
                newKey.contains("multi_modal_projector")
            {
                continue
            }

            result[newKey] = value
        }

        // Weight tying fallback: copy embed_tokens to lm_head if missing
        if result["lm_head.weight"] == nil {
            for suffix in ["weight", "scales", "biases"] {
                if let embedWeight = result["model.embed_tokens.\(suffix)"] {
                    result["lm_head.\(suffix)"] = embedWeight
                }
            }
        }

        return result
    }
}
