//
//  GptOssGenerated.swift
//  NodeMLXCore
//
//  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
//  Generated by hf2swift from model patterns.
//  Re-run the generator to update this file.
//
//  Based on patterns from mlx-lm and mlx-swift-lm.
//

import Foundation
import MLX
import MLXFast
import MLXNN

// MARK: - Configuration

public struct GptOSSConfiguration: Decodable, Sendable {
    public var hiddenSize: Int
    public var numHiddenLayers: Int
    public var numAttentionHeads: Int
    public var numKeyValueHeads: Int
    public var intermediateSize: Int
    public var vocabSize: Int
    public var headDim: Int
    public var rmsNormEps: Float
    public var ropeTheta: Float
    public var maxPositionEmbeddings: Int
    public var attentionBias: Bool
    public var mlpBias: Bool

    // Mixture of Experts configuration
    public var numLocalExperts: Int
    public var numExpertsPerTok: Int
    public var slidingWindow: Int
    public var slidingWindowPattern: Int
    public var layerTypes: [String]
    public var ropeScaling: [String: StringOrNumber]?
    public var modelType: String?

    /// Check if a layer is a global attention layer
    public func isGlobalLayer(_ layerIdx: Int) -> Bool {
        if layerIdx < layerTypes.count {
            let layerType = layerTypes[layerIdx].lowercased()
            return layerType == "full_attention" || layerType == "global"
        }
        return false
    }

    enum CodingKeys: String, CodingKey {
        case textConfig = "text_config"
        case hiddenSize = "hidden_size"
        case numHiddenLayers = "num_hidden_layers"
        case numAttentionHeads = "num_attention_heads"
        case numKeyValueHeads = "num_key_value_heads"
        case intermediateSize = "intermediate_size"
        case vocabSize = "vocab_size"
        case headDim = "head_dim"
        case rmsNormEps = "rms_norm_eps"
        case ropeTheta = "rope_theta"
        case maxPositionEmbeddings = "max_position_embeddings"
        case attentionBias = "attention_bias"
        case mlpBias = "mlp_bias"
        case numLocalExperts = "num_local_experts"
        case numExpertsPerTok = "num_experts_per_tok"
        case slidingWindow = "sliding_window"
        case slidingWindowPattern = "sliding_window_pattern"
        case layerTypes = "layer_types"
        case ropeScaling = "rope_scaling"
        case modelType = "model_type"
    }

    public init(from decoder: Swift.Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        // Helper to decode from text_config or top level
        func decode<T: Decodable>(_ key: CodingKeys, default defaultValue: T? = nil) throws -> T {
            if let nested = try? container.nestedContainer(keyedBy: CodingKeys.self, forKey: .textConfig),
               let value = try? nested.decode(T.self, forKey: key)
            {
                return value
            }
            if let value = try? container.decode(T.self, forKey: key) {
                return value
            }
            if let defaultValue {
                return defaultValue
            }
            throw DecodingError.keyNotFound(key, DecodingError.Context(codingPath: [], debugDescription: "Missing \(key)"))
        }

        hiddenSize = try decode(.hiddenSize)
        numHiddenLayers = try decode(.numHiddenLayers)
        numAttentionHeads = try decode(.numAttentionHeads)
        numKeyValueHeads = try decode(.numKeyValueHeads, default: numAttentionHeads)

        intermediateSize = try decode(.intermediateSize)

        vocabSize = try decode(.vocabSize)
        headDim = try decode(.headDim, default: hiddenSize / numAttentionHeads)
        rmsNormEps = try decode(.rmsNormEps, default: 1e-6)
        ropeTheta = try decode(.ropeTheta, default: 10000.0)
        maxPositionEmbeddings = try decode(.maxPositionEmbeddings, default: 32768)
        attentionBias = try decode(.attentionBias, default: true)
        mlpBias = try decode(.mlpBias, default: true)

        // MoE configuration
        numLocalExperts = try decode(.numLocalExperts, default: 32)
        numExpertsPerTok = try decode(.numExpertsPerTok, default: 4)

        slidingWindow = try decode(.slidingWindow, default: 512)
        slidingWindowPattern = try decode(.slidingWindowPattern, default: 6)

        if let types: [String] = try? decode(.layerTypes) {
            layerTypes = types
        } else {
            layerTypes = (0 ..< numHiddenLayers).map { $0 % 2 == 0 ? "sliding_attention" : "full_attention" }
        }

        ropeScaling = try? container.decode([String: StringOrNumber].self, forKey: .ropeScaling)
        modelType = try? container.decode(String.self, forKey: .modelType)
    }
}

// MARK: - RMS Norm

/// Standard RMSNorm
class GptOSSRMSNorm: Module {
    let eps: Float

    @ModuleInfo(key: "weight") var weight: MLXArray

    init(dimensions: Int, eps: Float = 1e-6) {
        self.eps = eps
        _weight.wrappedValue = MLXArray.ones([dimensions])
    }

    func callAsFunction(_ x: MLXArray) -> MLXArray {
        MLXFast.rmsNorm(x, weight: weight, eps: eps)
    }
}

// MARK: - Utility Functions

// MARK: - Attention

class GptOSSAttention: Module {
    @ModuleInfo(key: "q_proj") var qProj: Linear
    @ModuleInfo(key: "k_proj") var kProj: Linear
    @ModuleInfo(key: "v_proj") var vProj: Linear
    @ModuleInfo(key: "o_proj") var oProj: Linear
    @ModuleInfo(key: "sinks") var sinks: MLXArray

    let numHeads: Int
    let numKVHeads: Int
    let headDim: Int
    let scale: Float
    let rope: RoPE
    let isSliding: Bool

    init(_ config: GptOSSConfiguration, layerIdx: Int) {
        numHeads = config.numAttentionHeads
        numKVHeads = config.numKeyValueHeads
        headDim = config.headDim
        scale = 1.0 / sqrt(Float(headDim))

        let qDim = numHeads * headDim
        let kvDim = numKVHeads * headDim
        let attnBias = config.attentionBias

        _qProj.wrappedValue = Linear(config.hiddenSize, qDim, bias: attnBias)
        _kProj.wrappedValue = Linear(config.hiddenSize, kvDim, bias: attnBias)
        _vProj.wrappedValue = Linear(config.hiddenSize, kvDim, bias: attnBias)
        _oProj.wrappedValue = Linear(qDim, config.hiddenSize, bias: attnBias)
        _sinks.wrappedValue = MLXArray.zeros([numHeads])
        isSliding = !config.isGlobalLayer(layerIdx)
        let ropeBase = config.ropeTheta
        rope = RoPE(dimensions: headDim, traditional: false, base: ropeBase)
    }

    func callAsFunction(
        _ hiddenStates: MLXArray,
        mask: MLXFast.ScaledDotProductAttentionMaskMode,
        cache: inout KVCache?
    ) -> MLXArray {
        let (B, L, _) = (hiddenStates.dim(0), hiddenStates.dim(1), hiddenStates.dim(2))

        var queries = qProj(hiddenStates).reshaped([B, L, numHeads, headDim])
        var keys = kProj(hiddenStates).reshaped([B, L, numKVHeads, headDim])
        var values = vProj(hiddenStates).reshaped([B, L, numKVHeads, headDim])

        // Transpose for attention: [B, heads, L, headDim]
        queries = queries.transposed(0, 2, 1, 3)
        keys = keys.transposed(0, 2, 1, 3)
        values = values.transposed(0, 2, 1, 3)

        // Apply RoPE with cache offset
        let offset = cache?.offset ?? 0
        queries = rope.apply(queries, offset: offset)
        keys = rope.apply(keys, offset: offset)

        // Update cache
        if let c = cache {
            (keys, values) = c.update(keys: keys, values: values)
        }

        // Attention using MLXFast (handles GQA automatically)
        let output = MLXFast.scaledDotProductAttention(
            queries: queries,
            keys: keys,
            values: values,
            scale: scale,
            mask: mask
        )

        // Reshape back: [B, heads, L, headDim] -> [B, L, hidden]
        let outputReshaped = output.transposed(0, 2, 1, 3).reshaped([B, L, -1])
        return oProj(outputReshaped)
    }
}

// MARK: - MoE MLP

/// Mixture of Experts MLP using shared MoEMLP infrastructure
class GptOSSMLP: Module {
    @ModuleInfo(key: "router") var router: MoERouter
    @ModuleInfo(key: "experts") var experts: SwitchGLU

    let numExperts: Int
    let topK: Int

    init(_ config: GptOSSConfiguration) {
        numExperts = config.numLocalExperts
        topK = config.numExpertsPerTok

        _router.wrappedValue = MoERouter(
            hiddenSize: config.hiddenSize,
            numExperts: config.numLocalExperts,
            topK: config.numExpertsPerTok,
            bias: config.mlpBias
        )
        _experts.wrappedValue = SwitchGLU(
            inputDims: config.hiddenSize,
            hiddenDims: config.intermediateSize,
            numExperts: config.numLocalExperts,
            bias: config.mlpBias,
            useCustomSwiGLU: true
        )
    }

    func callAsFunction(_ x: MLXArray) -> MLXArray {
        let shape = x.shape
        let batchSeq = shape.dropLast().reduce(1, *)
        let hidden = shape.last!

        // Flatten to [batch * seq, hidden]
        let xFlat = x.reshaped([batchSeq, hidden])

        // Get routing weights and expert indices
        let (weights, indices) = router(xFlat)

        // Get expert outputs [batch * seq, topK, hidden]
        let expertOutput = experts(xFlat, indices: indices)

        // Weighted sum of expert outputs
        let weightsExpanded = weights[.ellipsis, .newAxis]
        let weightedOutput = sum(expertOutput * weightsExpanded, axis: 1)

        // Reshape back to original shape
        return weightedOutput.reshaped(shape)
    }
}

// MARK: - Decoder Layer

class GptOSSDecoderLayer: Module {
    @ModuleInfo(key: "self_attn") var selfAttn: GptOSSAttention
    @ModuleInfo(key: "mlp") var mlp: GptOSSMLP
    @ModuleInfo(key: "input_layernorm") var inputLayernorm: GptOSSRMSNorm
    @ModuleInfo(key: "post_attention_layernorm") var postAttentionLayernorm: GptOSSRMSNorm

    init(_ config: GptOSSConfiguration, layerIdx: Int) {
        _selfAttn.wrappedValue = GptOSSAttention(config, layerIdx: layerIdx)
        _mlp.wrappedValue = GptOSSMLP(config)
        _inputLayernorm.wrappedValue = GptOSSRMSNorm(dimensions: config.hiddenSize, eps: config.rmsNormEps)
        _postAttentionLayernorm.wrappedValue = GptOSSRMSNorm(dimensions: config.hiddenSize, eps: config.rmsNormEps)
    }

    func callAsFunction(
        _ hiddenStates: MLXArray,
        mask: MLXFast.ScaledDotProductAttentionMaskMode,
        cache: inout KVCache?
    ) -> MLXArray {
        // 1. Pre-norm + Self-attention
        let normed = inputLayernorm(hiddenStates)
        let attnOut = selfAttn(normed, mask: mask, cache: &cache)
        var h = hiddenStates + attnOut

        // 2. Pre-norm + MLP
        let mlpNormed = postAttentionLayernorm(h)
        let mlpOut = mlp(mlpNormed)
        h = h + mlpOut
        return h
    }
}

// MARK: - Model Inner

class GptOSSModelInner: Module {
    @ModuleInfo(key: "embed_tokens") var embedTokens: Embedding
    @ModuleInfo(key: "layers") var layers: [GptOSSDecoderLayer]
    @ModuleInfo(key: "norm") var norm: GptOSSRMSNorm

    let numLayers: Int
    let hiddenSize: Int
    let slidingWindow: Int
    let layerTypes: [String]

    init(_ config: GptOSSConfiguration) {
        numLayers = config.numHiddenLayers
        hiddenSize = config.hiddenSize
        slidingWindow = config.slidingWindow
        layerTypes = config.layerTypes
        _embedTokens.wrappedValue = Embedding(embeddingCount: config.vocabSize, dimensions: config.hiddenSize)
        _layers.wrappedValue = (0 ..< numLayers).map { idx in GptOSSDecoderLayer(config, layerIdx: idx) }
        _norm.wrappedValue = GptOSSRMSNorm(dimensions: config.hiddenSize, eps: config.rmsNormEps)
    }

    func callAsFunction(_ inputIds: MLXArray, cache: inout [KVCache?]) -> MLXArray {
        var hiddenStates = embedTokens(inputIds)
        // Find first global layer for mask creation
        var firstGlobalIdx = 0
        for (i, layerType) in layerTypes.prefix(cache.count).enumerated() {
            if layerType == "full_attention" { firstGlobalIdx = i; break }
        }
        let globalCache = firstGlobalIdx < cache.count ? cache[firstGlobalIdx] : nil
        let globalMask = createAttentionMask(h: hiddenStates, cache: globalCache, windowSize: nil)
        let firstSlidingCache = cache.first ?? nil
        let slidingMask = createAttentionMask(h: hiddenStates, cache: firstSlidingCache, windowSize: slidingWindow)
        for i in 0 ..< layers.count {
            let layerType = i < layerTypes.count ? layerTypes[i] : "sliding_attention"
            let isGlobal = layerType == "full_attention"
            let mask = isGlobal ? globalMask : slidingMask
            hiddenStates = layers[i](hiddenStates, mask: mask, cache: &cache[i])
        }
        return norm(hiddenStates)
    }
}

// MARK: - Top-Level Model

public class GptOSSModel: Module, LLMModel {
    public let vocabularySize: Int
    public let numLayers: Int
    public let numKVHeads: Int
    public let headDim: Int

    @ModuleInfo(key: "model") var model: GptOSSModelInner
    @ModuleInfo(key: "lm_head") var lmHead: Linear

    private let config: GptOSSConfiguration

    public var supportsCache: Bool { true }

    public init(_ config: GptOSSConfiguration) {
        self.config = config
        vocabularySize = config.vocabSize
        numLayers = config.numHiddenLayers
        numKVHeads = config.numKeyValueHeads
        headDim = config.headDim
        _model.wrappedValue = GptOSSModelInner(config)
        _lmHead.wrappedValue = Linear(config.hiddenSize, config.vocabSize, bias: false)
    }

    public func callAsFunction(_ inputIds: MLXArray) -> MLXArray {
        var cache: [KVCache?] = Array(repeating: nil, count: numLayers)
        let h = model(inputIds, cache: &cache)
        return lmHead(h)
    }

    public func callAsFunction(_ inputIds: MLXArray, cache: inout [KVCache]?) -> MLXArray {
        var layerCaches: [KVCache?] = if let existingCache = cache { existingCache.map { $0 as KVCache? } }
        else { Array(repeating: nil, count: numLayers) }
        let h = model(inputIds, cache: &layerCaches)
        cache = layerCaches.compactMap(\.self)
        return lmHead(h)
    }

    public func newCache() -> [KVCache] {
        (0 ..< numLayers).map { i in
            let layerType = i < config.layerTypes.count ? config.layerTypes[i] : "sliding_attention"
            if layerType == "full_attention" { return KVCacheSimple() }
            else { return RotatingKVCache(maxSize: config.slidingWindow, keep: 0) }
        }
    }

    public func sanitize(weights: [String: MLXArray]) -> [String: MLXArray] {
        var result: [String: MLXArray] = [:]
        for (key, value) in weights {
            var newKey = key
            if newKey.hasPrefix("language_model.model.") { newKey = "model." + String(newKey.dropFirst("language_model.model.".count)) }
            else if newKey.hasPrefix("language_model.lm_head.") { newKey = "lm_head." + String(newKey.dropFirst("language_model.lm_head.".count)) }
            else if newKey.hasPrefix("language_model.") { newKey = String(newKey.dropFirst("language_model.".count)) }
            if newKey.contains("vision_tower") || newKey.contains("audio_tower") || newKey.contains("multi_modal_projector") { continue }
            // Map MoE expert weights to SwitchGLU format
            if newKey.contains(".mlp.experts.") {
                newKey = newKey.replacingOccurrences(of: ".experts.gate_proj.weight", with: ".experts.gate_proj")
                newKey = newKey.replacingOccurrences(of: ".experts.up_proj.weight", with: ".experts.up_proj")
                newKey = newKey.replacingOccurrences(of: ".experts.down_proj.weight", with: ".experts.down_proj")
                newKey = newKey.replacingOccurrences(of: ".experts.gate_proj.bias", with: ".experts.gate_proj_bias")
                newKey = newKey.replacingOccurrences(of: ".experts.up_proj.bias", with: ".experts.up_proj_bias")
                newKey = newKey.replacingOccurrences(of: ".experts.down_proj.bias", with: ".experts.down_proj_bias")
            }
            result[newKey] = value
        }
        if result["lm_head.weight"] == nil {
            for suffix in ["weight", "scales", "biases"] {
                if let embedWeight = result["model.embed_tokens.\(suffix)"] { result["lm_head.\(suffix)"] = embedWeight }
            }
        }
        return result
    }
}
