//
//  MistralGenerated.swift
//  NodeMLXCore
//
//  AUTO-GENERATED FILE - DO NOT EDIT MANUALLY!
//  Generated by hf2swift from model patterns.
//  Re-run the generator to update this file.
//
//  Based on patterns from mlx-lm and mlx-swift-lm.
//

import Foundation
import MLX
import MLXFast
import MLXNN

// MARK: - Configuration

public struct MistralConfiguration: Decodable, Sendable {
    public var hiddenSize: Int
    public var numHiddenLayers: Int
    public var numAttentionHeads: Int
    public var numKeyValueHeads: Int
    public var intermediateSize: Int
    public var vocabSize: Int
    public var headDim: Int
    public var rmsNormEps: Float
    public var ropeTheta: Float
    public var maxPositionEmbeddings: Int
    public var slidingWindow: Int
    public var slidingWindowPattern: Int
    public var ropeScaling: [String: StringOrNumber]?

    /// Check if a layer is a global attention layer
    public func isGlobalLayer(_ layerIdx: Int) -> Bool {
        (layerIdx % slidingWindowPattern) == (slidingWindowPattern - 1)
    }

    enum CodingKeys: String, CodingKey {
        case textConfig = "text_config"
        case hiddenSize = "hidden_size"
        case numHiddenLayers = "num_hidden_layers"
        case numAttentionHeads = "num_attention_heads"
        case numKeyValueHeads = "num_key_value_heads"
        case intermediateSize = "intermediate_size"
        case vocabSize = "vocab_size"
        case headDim = "head_dim"
        case rmsNormEps = "rms_norm_eps"
        case ropeTheta = "rope_theta"
        case maxPositionEmbeddings = "max_position_embeddings"
        case slidingWindow = "sliding_window"
        case slidingWindowPattern = "sliding_window_pattern"
        case ropeScaling = "rope_scaling"
    }

    public init(from decoder: Swift.Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        // Helper to decode from text_config or top level
        func decode<T: Decodable>(_ key: CodingKeys, default defaultValue: T? = nil) throws -> T {
            if let nested = try? container.nestedContainer(keyedBy: CodingKeys.self, forKey: .textConfig),
               let value = try? nested.decode(T.self, forKey: key)
            {
                return value
            }
            if let value = try? container.decode(T.self, forKey: key) {
                return value
            }
            if let defaultValue {
                return defaultValue
            }
            throw DecodingError.keyNotFound(key, DecodingError.Context(codingPath: [], debugDescription: "Missing \(key)"))
        }

        hiddenSize = try decode(.hiddenSize)
        numHiddenLayers = try decode(.numHiddenLayers)
        numAttentionHeads = try decode(.numAttentionHeads)
        numKeyValueHeads = try decode(.numKeyValueHeads, default: numAttentionHeads)
        intermediateSize = try decode(.intermediateSize)
        vocabSize = try decode(.vocabSize)
        headDim = try decode(.headDim, default: hiddenSize / numAttentionHeads)
        rmsNormEps = try decode(.rmsNormEps, default: 1e-6)
        ropeTheta = try decode(.ropeTheta, default: 10000.0)
        maxPositionEmbeddings = try decode(.maxPositionEmbeddings, default: 32768)
        slidingWindow = try decode(.slidingWindow, default: 512)
        slidingWindowPattern = try decode(.slidingWindowPattern, default: 6)
        ropeScaling = try? container.decode([String: StringOrNumber].self, forKey: .ropeScaling)
    }
}

// MARK: - RMS Norm

class MistralRMSNorm: Module {
    let eps: Float

    @ModuleInfo(key: "weight") var weight: MLXArray

    init(dimensions: Int, eps: Float = 1e-6) {
        self.eps = eps
        _weight.wrappedValue = MLXArray.ones([dimensions])
    }

    func callAsFunction(_ x: MLXArray) -> MLXArray {
        MLXFast.rmsNorm(x, weight: weight, eps: eps)
    }
}

// MARK: - Utility Functions

// MARK: - Attention

class MistralAttention: Module {
    @ModuleInfo(key: "q_proj") var qProj: Linear
    @ModuleInfo(key: "k_proj") var kProj: Linear
    @ModuleInfo(key: "v_proj") var vProj: Linear
    @ModuleInfo(key: "o_proj") var oProj: Linear

    let numHeads: Int
    let numKVHeads: Int
    let headDim: Int
    let scale: Float
    let rope: any RoPEProvider
    let isGlobal: Bool
    let slidingWindow: Int?

    init(_ config: MistralConfiguration, layerIdx: Int) {
        numHeads = config.numAttentionHeads
        numKVHeads = config.numKeyValueHeads
        headDim = config.headDim
        scale = 1.0 / sqrt(Float(headDim))

        let qDim = numHeads * headDim
        let kvDim = numKVHeads * headDim

        _qProj.wrappedValue = Linear(config.hiddenSize, qDim, bias: false)
        _kProj.wrappedValue = Linear(config.hiddenSize, kvDim, bias: false)
        _vProj.wrappedValue = Linear(config.hiddenSize, kvDim, bias: false)
        _oProj.wrappedValue = Linear(qDim, config.hiddenSize, bias: false)

        isGlobal = config.isGlobalLayer(layerIdx)
        slidingWindow = isGlobal ? nil : config.slidingWindow

        // Different RoPE theta for sliding vs global layers
        let ropeBase = config.ropeTheta

        // Use initializeRope to handle linear scaling for larger models
        rope = initializeRope(
            dims: headDim,
            base: ropeBase,
            traditional: false,
            scalingConfig: isGlobal ? config.ropeScaling : nil,
            maxPositionEmbeddings: config.maxPositionEmbeddings
        )
    }

    func callAsFunction(
        _ hiddenStates: MLXArray,
        mask: MLXFast.ScaledDotProductAttentionMaskMode,
        cache: inout KVCache?
    ) -> MLXArray {
        let (B, L, _) = (hiddenStates.dim(0), hiddenStates.dim(1), hiddenStates.dim(2))

        // Project to Q, K, V and reshape
        var queries = qProj(hiddenStates).reshaped([B, L, numHeads, headDim])
        var keys = kProj(hiddenStates).reshaped([B, L, numKVHeads, headDim])
        var values = vProj(hiddenStates).reshaped([B, L, numKVHeads, headDim])

        // Transpose for attention: [B, heads, L, headDim]
        queries = queries.transposed(0, 2, 1, 3)
        keys = keys.transposed(0, 2, 1, 3)
        values = values.transposed(0, 2, 1, 3)

        // Apply RoPE with cache offset
        let offset = cache?.offset ?? 0
        queries = rope.apply(queries, offset: offset)
        keys = rope.apply(keys, offset: offset)

        // Update cache
        if let c = cache {
            (keys, values) = c.update(keys: keys, values: values)
        }

        // Attention using MLXFast (handles GQA automatically)
        let output = MLXFast.scaledDotProductAttention(
            queries: queries,
            keys: keys,
            values: values,
            scale: scale,
            mask: mask
        )

        // Reshape back: [B, heads, L, headDim] -> [B, L, hidden]
        let outputReshaped = output.transposed(0, 2, 1, 3).reshaped([B, L, -1])

        return oProj(outputReshaped)
    }
}

// MARK: - MLP

class MistralMLP: Module {
    @ModuleInfo(key: "gate_proj") var gateProj: Linear
    @ModuleInfo(key: "up_proj") var upProj: Linear
    @ModuleInfo(key: "down_proj") var downProj: Linear

    init(_ config: MistralConfiguration) {
        _gateProj.wrappedValue = Linear(config.hiddenSize, config.intermediateSize, bias: false)
        _upProj.wrappedValue = Linear(config.hiddenSize, config.intermediateSize, bias: false)
        _downProj.wrappedValue = Linear(config.intermediateSize, config.hiddenSize, bias: false)
    }

    func callAsFunction(_ x: MLXArray) -> MLXArray {
        downProj(silu(gateProj(x)) * upProj(x))
    }
}

// MARK: - Decoder Layer

class MistralDecoderLayer: Module {
    @ModuleInfo(key: "self_attn") var selfAttn: MistralAttention
    @ModuleInfo(key: "mlp") var mlp: MistralMLP
    @ModuleInfo(key: "input_layernorm") var inputLayernorm: MistralRMSNorm
    @ModuleInfo(key: "post_attention_layernorm") var postAttentionLayernorm: MistralRMSNorm

    init(_ config: MistralConfiguration, layerIdx: Int) {
        _selfAttn.wrappedValue = MistralAttention(config, layerIdx: layerIdx)
        _mlp.wrappedValue = MistralMLP(config)
        _inputLayernorm.wrappedValue = MistralRMSNorm(dimensions: config.hiddenSize, eps: config.rmsNormEps)
        _postAttentionLayernorm.wrappedValue = MistralRMSNorm(dimensions: config.hiddenSize, eps: config.rmsNormEps)
    }

    func callAsFunction(
        _ hiddenStates: MLXArray,
        mask: MLXFast.ScaledDotProductAttentionMaskMode,
        cache: inout KVCache?
    ) -> MLXArray {
        // 1. Pre-norm + Self-attention
        let normed = inputLayernorm(hiddenStates)
        let attnOut = selfAttn(normed, mask: mask, cache: &cache)
        var h = hiddenStates + attnOut

        // 2. Pre-norm + MLP
        let mlpNormed = postAttentionLayernorm(h)
        let mlpOut = mlp(mlpNormed)
        h = h + mlpOut

        return h
    }
}

// MARK: - Model Inner

class MistralModelInner: Module {
    @ModuleInfo(key: "embed_tokens") var embedTokens: Embedding
    @ModuleInfo(key: "layers") var layers: [MistralDecoderLayer]
    @ModuleInfo(key: "norm") var norm: MistralRMSNorm

    let numLayers: Int
    let hiddenSize: Int
    let slidingWindow: Int
    let slidingWindowPattern: Int

    init(_ config: MistralConfiguration) {
        numLayers = config.numHiddenLayers
        hiddenSize = config.hiddenSize
        slidingWindow = config.slidingWindow
        slidingWindowPattern = config.slidingWindowPattern
        _embedTokens.wrappedValue = Embedding(embeddingCount: config.vocabSize, dimensions: config.hiddenSize)
        _layers.wrappedValue = (0 ..< numLayers).map { idx in MistralDecoderLayer(config, layerIdx: idx) }
        _norm.wrappedValue = MistralRMSNorm(dimensions: config.hiddenSize, eps: config.rmsNormEps)
    }

    func callAsFunction(
        _ inputIds: MLXArray,
        cache: inout [KVCache?]
    ) -> MLXArray {
        var hiddenStates = embedTokens(inputIds)

        // Create masks following mlx-lm pattern:
        // - Global mask: uses cache from a global layer (pattern - 1)
        // - Sliding mask: uses cache from first layer with sliding window size
        let globalLayerIdx = slidingWindowPattern - 1
        let globalCache = globalLayerIdx < cache.count ? cache[globalLayerIdx] : nil
        let globalMask = createAttentionMask(h: hiddenStates, cache: globalCache, windowSize: nil)

        // Sliding window mask (only if pattern > 1)
        let slidingMask: MLXFast.ScaledDotProductAttentionMaskMode
        if slidingWindowPattern > 1 {
            let firstCache = cache.first ?? nil
            slidingMask = createAttentionMask(h: hiddenStates, cache: firstCache, windowSize: slidingWindow)
        } else {
            slidingMask = globalMask
        }

        for i in 0 ..< layers.count {
            // Layer is global if i % pattern == pattern - 1 (matching mlx-lm)
            let isGlobal = (i % slidingWindowPattern) == (slidingWindowPattern - 1)
            let mask = isGlobal ? globalMask : slidingMask
            hiddenStates = layers[i](hiddenStates, mask: mask, cache: &cache[i])
        }

        return norm(hiddenStates)
    }
}

// MARK: - Top-Level Model

public class MistralModel: Module, LLMModel {
    public let vocabularySize: Int
    public let numLayers: Int
    public let numKVHeads: Int
    public let headDim: Int

    @ModuleInfo(key: "model") var model: MistralModelInner
    @ModuleInfo(key: "lm_head") var lmHead: Linear

    private let config: MistralConfiguration

    public var supportsCache: Bool { true }

    public init(_ config: MistralConfiguration) {
        self.config = config
        vocabularySize = config.vocabSize
        numLayers = config.numHiddenLayers
        numKVHeads = config.numKeyValueHeads
        headDim = config.headDim

        _model.wrappedValue = MistralModelInner(config)
        _lmHead.wrappedValue = Linear(config.hiddenSize, config.vocabSize, bias: false)
    }

    /// Forward pass without cache
    public func callAsFunction(_ inputIds: MLXArray) -> MLXArray {
        var cache: [KVCache?] = Array(repeating: nil, count: numLayers)
        let h = model(inputIds, cache: &cache)
        return lmHead(h)
    }

    /// Forward pass with KV cache for efficient generation
    public func callAsFunction(_ inputIds: MLXArray, cache: inout [KVCache]?) -> MLXArray {
        var layerCaches: [KVCache?] = if let existingCache = cache {
            existingCache.map { $0 as KVCache? }
        } else {
            Array(repeating: nil, count: numLayers)
        }

        let h = model(inputIds, cache: &layerCaches)

        cache = layerCaches.compactMap(\.self)

        return lmHead(h)
    }

    /// Create a new KV cache with appropriate cache types per layer
    /// Following mlx-lm pattern: global layers use KVCacheSimple, others use RotatingKVCache
    public func newCache() -> [KVCache] {
        (0 ..< numLayers).map { i in
            // Layer is global if i % pattern == pattern - 1
            let isGlobal = (i % config.slidingWindowPattern) == (config.slidingWindowPattern - 1)
            if isGlobal {
                return KVCacheSimple()
            } else {
                return RotatingKVCache(maxSize: config.slidingWindow, keep: 0)
            }
        }
    }

    /// Sanitize weight keys from HuggingFace format
    public func sanitize(weights: [String: MLXArray]) -> [String: MLXArray] {
        var result: [String: MLXArray] = [:]

        for (key, value) in weights {
            var newKey = key

            // VLM format transformations:
            // - language_model.model.X -> model.X (transformer layers)
            // - language_model.lm_head.X -> lm_head.X (output projection)
            // - language_model.X -> X (other components)
            if newKey.hasPrefix("language_model.model.") {
                newKey = "model." + String(newKey.dropFirst("language_model.model.".count))
            } else if newKey.hasPrefix("language_model.lm_head.") {
                newKey = "lm_head." + String(newKey.dropFirst("language_model.lm_head.".count))
            } else if newKey.hasPrefix("language_model.") {
                newKey = String(newKey.dropFirst("language_model.".count))
            }

            // Skip vision/audio tower weights
            if newKey.contains("vision_tower") || newKey.contains("audio_tower") ||
                newKey.contains("multi_modal_projector")
            {
                continue
            }

            result[newKey] = value
        }

        // Weight tying fallback: copy embed_tokens to lm_head if missing
        if result["lm_head.weight"] == nil {
            for suffix in ["weight", "scales", "biases"] {
                if let embedWeight = result["model.embed_tokens.\(suffix)"] {
                    result["lm_head.\(suffix)"] = embedWeight
                }
            }
        }

        return result
    }
}
