//
//  Phi3.swift
//  Auto-generated by hf2swift v5
//
//  This file was generated from HuggingFace Transformers source code.
//  The structure follows patterns from mlx-swift-lm (MIT License, ml-explore).
//  See: https://github.com/ml-explore/mlx-swift-lm
//

import Foundation
import MLX
import MLXFast
import MLXNN

// Note: KVCache and LLMModel protocols are defined in NodeMLXCore
// Import them if using this as a standalone file

// MARK: - Configuration

public struct Phi3Configuration: Codable, Sendable {
    public let attentionBias: Bool?
    public let attentionDropout: Float?
    public let bosTokenId: Int?
    public let embdPdrop: Float?
    public let eosTokenId: Int?
    public let hiddenAct: String?
    public var hiddenSize: Int
    public let initializerRange: Float?
    public var intermediateSize: Int
    public let maxPositionEmbeddings: Int?
    public var modelType: String
    public var numAttentionHeads: Int
    public var numHiddenLayers: Int
    public let numKeyValueHeads: Int?
    public let originalMaxPositionEmbeddings: Int?
    public let padTokenId: Int?
    public let residPdrop: Float?
    public let rmsNormEps: Float?
    public let ropeTheta: Float?
    public let slidingWindow: Int?
    public let tieWordEmbeddings: Bool?
    public let useCache: Bool?
    public var vocabSize: Int

    enum CodingKeys: String, CodingKey {
        case attentionBias = "attention_bias"
        case attentionDropout = "attention_dropout"
        case bosTokenId = "bos_token_id"
        case embdPdrop = "embd_pdrop"
        case eosTokenId = "eos_token_id"
        case hiddenAct = "hidden_act"
        case hiddenSize = "hidden_size"
        case initializerRange = "initializer_range"
        case intermediateSize = "intermediate_size"
        case maxPositionEmbeddings = "max_position_embeddings"
        case modelType = "model_type"
        case numAttentionHeads = "num_attention_heads"
        case numHiddenLayers = "num_hidden_layers"
        case numKeyValueHeads = "num_key_value_heads"
        case originalMaxPositionEmbeddings = "original_max_position_embeddings"
        case padTokenId = "pad_token_id"
        case residPdrop = "resid_pdrop"
        case rmsNormEps = "rms_norm_eps"
        case ropeTheta = "rope_theta"
        case slidingWindow = "sliding_window"
        case tieWordEmbeddings = "tie_word_embeddings"
        case useCache = "use_cache"
        case vocabSize = "vocab_size"
    }

    // Computed properties
    public var headDim: Int {
        hiddenSize / numAttentionHeads
    }
}

// MARK: - Helper Functions

/// Apply rotary position embeddings for Phi3
private func phi3ApplyRotaryPosEmb(
    _ q: MLXArray,
    _ k: MLXArray,
    cos: MLXArray,
    sin: MLXArray
) -> (MLXArray, MLXArray) {
    let qEmbed = (q * cos) + (phi3RotateHalf(q) * sin)
    let kEmbed = (k * cos) + (phi3RotateHalf(k) * sin)
    return (qEmbed, kEmbed)
}

/// Rotate half of the tensor for Phi3
private func phi3RotateHalf(_ x: MLXArray) -> MLXArray {
    let halfDim = x.dim(-1) / 2
    let x1 = x[.ellipsis, ..<halfDim]
    let x2 = x[.ellipsis, halfDim...]
    return concatenated([-x2, x1], axis: -1)
}

// MARK: - Model Components

// MARK: - Phi3Attention

class Phi3Attention: Module {
    // Phi3 uses fused QKV projection
    @ModuleInfo(key: "qkv_proj") var qkvProj: Linear
    @ModuleInfo(key: "o_proj") var oProj: Linear

    let numHeads: Int
    let numKVHeads: Int
    let headDim: Int
    let scale: Float
    let rope: RoPE

    init(_ config: Phi3Configuration) {
        let hiddenSize = config.hiddenSize
        self.numHeads = config.numAttentionHeads
        self.numKVHeads = config.numKeyValueHeads ?? config.numAttentionHeads
        self.headDim = config.headDim
        self.scale = 1.0 / sqrt(Float(headDim))

        // Phi3 has fused QKV: output dim = (numHeads + 2 * numKVHeads) * headDim
        let qkvDim = (numHeads + 2 * numKVHeads) * headDim
        self._qkvProj.wrappedValue = Linear(hiddenSize, qkvDim, bias: false)
        self._oProj.wrappedValue = Linear(numHeads * headDim, hiddenSize, bias: false)

        // Initialize RoPE
        self.rope = RoPE(
            dimensions: headDim,
            traditional: false,
            base: config.ropeTheta ?? 10000
        )
    }

    func callAsFunction(
        _ x: MLXArray,
        mask: MLXArray? = nil,
        cache: inout KVCache?
    ) -> MLXArray {
        let (B, L, _) = (x.dim(0), x.dim(1), x.dim(2))

        // Fused QKV projection
        let qkv = qkvProj(x)

        // Split into Q, K, V
        let qSize = numHeads * headDim
        let kvSize = numKVHeads * headDim

        var queries = qkv[.ellipsis, ..<qSize]
        var keys = qkv[.ellipsis, qSize..<(qSize + kvSize)]
        var values = qkv[.ellipsis, (qSize + kvSize)...]

        // Reshape: [B, L, H*D] -> [B, H, L, D]
        queries = queries.reshaped([B, L, numHeads, headDim]).transposed(0, 2, 1, 3)
        keys = keys.reshaped([B, L, numKVHeads, headDim]).transposed(0, 2, 1, 3)
        values = values.reshaped([B, L, numKVHeads, headDim]).transposed(0, 2, 1, 3)

        // Apply RoPE with cache offset
        queries = rope(queries, offset: cache?.offset ?? 0)
        keys = rope(keys, offset: cache?.offset ?? 0)

        // Update cache and get full key/value history
        var cachedKeys = keys
        var cachedValues = values
        if let c = cache {
            (cachedKeys, cachedValues) = c.update(keys: keys, values: values)
        }

        // Repeat KV heads if using GQA
        if numKVHeads < numHeads {
            let repeats = numHeads / numKVHeads
            cachedKeys = MLXArray.repeated(cachedKeys, count: repeats, axis: 1)
            cachedValues = MLXArray.repeated(cachedValues, count: repeats, axis: 1)
        }

        // Scaled dot-product attention
        let maskMode: MLXFast.ScaledDotProductAttentionMaskMode = mask != nil ? .array(mask!) : .none
        let output = MLXFast.scaledDotProductAttention(
            queries: queries,
            keys: cachedKeys,
            values: cachedValues,
            scale: scale,
            mask: maskMode
        )

        // Reshape back: [B, H, L, D] -> [B, L, H*D]
        let outputReshaped = output.transposed(0, 2, 1, 3).reshaped([B, L, numHeads * headDim])

        return oProj(outputReshaped)
    }
}

// MARK: - Phi3MLP

class Phi3MLP: Module {
    // Phi3 uses fused gate_up_proj
    @ModuleInfo(key: "gate_up_proj") var gateUpProj: Linear
    @ModuleInfo(key: "down_proj") var downProj: Linear

    let intermediateSize: Int

    init(_ config: Phi3Configuration) {
        let hiddenSize = config.hiddenSize
        self.intermediateSize = config.intermediateSize
        // Fused gate+up: output = 2 * intermediateSize
        self._gateUpProj.wrappedValue = Linear(hiddenSize, 2 * intermediateSize, bias: false)
        self._downProj.wrappedValue = Linear(intermediateSize, hiddenSize, bias: false)
    }

    func callAsFunction(_ x: MLXArray) -> MLXArray {
        let gateUp = gateUpProj(x)
        let gate = gateUp[.ellipsis, ..<intermediateSize]
        let up = gateUp[.ellipsis, intermediateSize...]
        return downProj(silu(gate) * up)
    }
}

// MARK: - Phi3RMSNorm (using built-in RMSNorm)

// Note: Using MLXNN.RMSNorm directly

// MARK: - Phi3TransformerBlock

class Phi3TransformerBlock: Module {
    @ModuleInfo(key: "self_attn") var attention: Phi3Attention
    let mlp: Phi3MLP
    @ModuleInfo(key: "input_layernorm") var inputLayerNorm: RMSNorm
    @ModuleInfo(key: "post_attention_layernorm") var postAttentionLayerNorm: RMSNorm

    init(_ config: Phi3Configuration) {
        self._attention.wrappedValue = Phi3Attention(config)
        self.mlp = Phi3MLP(config)
        self._inputLayerNorm.wrappedValue = RMSNorm(
            dimensions: config.hiddenSize, eps: config.rmsNormEps ?? 1e-6)
        self._postAttentionLayerNorm.wrappedValue = RMSNorm(
            dimensions: config.hiddenSize, eps: config.rmsNormEps ?? 1e-6)
    }

    func callAsFunction(
        _ x: MLXArray,
        mask: MLXArray? = nil,
        cache: inout KVCache?
    ) -> MLXArray {
        // Self-attention with residual
        let residual1 = x
        let h1 = inputLayerNorm(x)
        let attnOut = attention(h1, mask: mask, cache: &cache)
        let h2 = residual1 + attnOut

        // MLP with residual
        let residual2 = h2
        let h3 = postAttentionLayerNorm(h2)
        let mlpOut = mlp(h3)
        return residual2 + mlpOut
    }
}

// MARK: - Phi3ModelInner

public class Phi3ModelInner: Module {
    @ModuleInfo(key: "embed_tokens") var embedTokens: Embedding
    let layers: [Phi3TransformerBlock]
    @ModuleInfo(key: "norm") var norm: RMSNorm

    public init(_ config: Phi3Configuration) {
        self._embedTokens.wrappedValue = Embedding(
            embeddingCount: config.vocabSize,
            dimensions: config.hiddenSize
        )
        self.layers = (0..<config.numHiddenLayers).map { _ in
            Phi3TransformerBlock(config)
        }
        self._norm.wrappedValue = RMSNorm(
            dimensions: config.hiddenSize, eps: config.rmsNormEps ?? 1e-6)
    }

    public func callAsFunction(
        _ inputIds: MLXArray,
        mask: MLXArray? = nil,
        cache: inout [KVCache?]
    ) -> MLXArray {
        var h = embedTokens(inputIds)

        for i in 0..<layers.count {
            h = layers[i](h, mask: mask, cache: &cache[i])
        }

        return norm(h)
    }
}

// MARK: - Phi3Model

public class Phi3Model: Module, LLMModel {
    public let vocabularySize: Int
    public let numLayers: Int
    public let numKVHeads: Int
    public let headDim: Int

    public let model: Phi3ModelInner
    @ModuleInfo(key: "lm_head") var lmHead: Linear
    private let config: Phi3Configuration

    public var supportsCache: Bool { true }

    public init(_ config: Phi3Configuration) {
        self.config = config
        self.vocabularySize = config.vocabSize
        self.numLayers = config.numHiddenLayers
        self.numKVHeads = config.numKeyValueHeads ?? config.numAttentionHeads
        self.headDim = config.headDim
        self.model = Phi3ModelInner(config)
        self._lmHead.wrappedValue = Linear(config.hiddenSize, config.vocabSize, bias: false)
    }

    /// Embed input tokens
    public func embed(_ inputIds: MLXArray) -> MLXArray {
        return model.embedTokens(inputIds)
    }

    /// Forward pass: compute logits from input token IDs
    public func callAsFunction(_ inputIds: MLXArray) -> MLXArray {
        var cache: [KVCache?] = Array(repeating: nil, count: numLayers)
        let h = model(inputIds, mask: nil, cache: &cache)
        return lmHead(h)
    }

    /// Forward pass with KV cache for efficient generation
    public func callAsFunction(_ inputIds: MLXArray, cache: inout [KVCache]?) -> MLXArray {
        // Convert [KVCache]? to [KVCache?]
        var layerCaches: [KVCache?]
        if let existingCache = cache {
            layerCaches = existingCache.map { $0 as KVCache? }
        } else {
            layerCaches = Array(repeating: nil, count: numLayers)
        }

        let mask = createCausalMask(n: inputIds.dim(1), offset: layerCaches.first??.offset ?? 0)
        let h = model(inputIds, mask: mask, cache: &layerCaches)

        // Convert back
        cache = layerCaches.compactMap { $0 }

        return lmHead(h)
    }

    /// Create a new KV cache for this model
    public func newCache() -> [KVCache] {
        return createLayerCaches(numLayers: numLayers)
    }

    /// Sanitize weight keys during model loading
    public func sanitize(weights: [String: MLXArray]) -> [String: MLXArray] {
        // Override in subclass if weight key mapping needed
        return weights
    }
}