//
//  Gemma3n.swift
//  Auto-generated by hf2swift v5
//
//  This file was generated from HuggingFace Transformers source code.
//  The structure follows patterns from mlx-swift-lm (MIT License, ml-explore).
//  See: https://github.com/ml-explore/mlx-swift-lm
//

import Foundation
import MLX
import MLXFast
import MLXNN

// Note: KVCache and LLMModel protocols are defined in NodeMLXCore
// Import them if using this as a standalone file

// MARK: - Configuration

public struct Gemma3nConfiguration: Decodable, Sendable {
    public let activationSparsityPattern: [Float]?
    public let altupActiveIdx: Int?
    public let altupCoefClip: Float?
    public let altupCorrectScale: Bool?
    public let altupLrMultiplier: Float?
    public let altupNumInputs: Int?
    public var attentionBias: Bool
    public let attentionDropout: Float?
    public let finalLogitSoftcapping: Float?
    public var headDim: Int
    public let hiddenActivation: String?
    public var hiddenSize: Int
    public let hiddenSizePerLayerInput: Int?
    public let initializerRange: Float?
    public var intermediateSize: Int
    public let laurelRank: Int?
    public let layerTypes: [String]?
    public var maxPositionEmbeddings: Int
    public var modelType: String
    public var numAttentionHeads: Int
    public var numHiddenLayers: Int
    public var numKeyValueHeads: Int
    public let numKvSharedLayers: Int?
    public let queryPreAttnScalar: Int?
    public var rmsNormEps: Float
    public let ropeLocalBaseFreq: Float?
    public var ropeTheta: Float
    public var slidingWindow: Int
    public let torchDtype: String?
    public let useCache: Bool?
    public var vocabSize: Int
    public let vocabSizePerLayerInput: Int?
    public let audioSoftTokensPerImage: Int?
    public let audioTokenId: Int?
    public let boaTokenId: Int?
    public let boiTokenId: Int?
    public let eoaTokenId: Int?
    public let eoiTokenId: Int?
    public let eosTokenId: [Int]
    public let imageTokenId: Int?
    public let visionSoftTokensPerImage: Int?

    // Top-level coding keys
    enum CodingKeys: String, CodingKey {
        case textConfig = "text_config"
        case audioSoftTokensPerImage = "audio_soft_tokens_per_image"
        case audioTokenId = "audio_token_id"
        case boaTokenId = "boa_token_id"
        case boiTokenId = "boi_token_id"
        case eoaTokenId = "eoa_token_id"
        case eoiTokenId = "eoi_token_id"
        case eosTokenId = "eos_token_id"
        case imageTokenId = "image_token_id"
        case visionSoftTokensPerImage = "vision_soft_tokens_per_image"
    }

    // Nested text_config coding keys
    enum TextConfigCodingKeys: String, CodingKey {
        case activationSparsityPattern = "activation_sparsity_pattern"
        case altupActiveIdx = "altup_active_idx"
        case altupCoefClip = "altup_coef_clip"
        case altupCorrectScale = "altup_correct_scale"
        case altupLrMultiplier = "altup_lr_multiplier"
        case altupNumInputs = "altup_num_inputs"
        case attentionBias = "attention_bias"
        case attentionDropout = "attention_dropout"
        case finalLogitSoftcapping = "final_logit_softcapping"
        case headDim = "head_dim"
        case hiddenActivation = "hidden_activation"
        case hiddenSize = "hidden_size"
        case hiddenSizePerLayerInput = "hidden_size_per_layer_input"
        case initializerRange = "initializer_range"
        case intermediateSize = "intermediate_size"
        case laurelRank = "laurel_rank"
        case layerTypes = "layer_types"
        case maxPositionEmbeddings = "max_position_embeddings"
        case modelType = "model_type"
        case numAttentionHeads = "num_attention_heads"
        case numHiddenLayers = "num_hidden_layers"
        case numKeyValueHeads = "num_key_value_heads"
        case numKvSharedLayers = "num_kv_shared_layers"
        case queryPreAttnScalar = "query_pre_attn_scalar"
        case rmsNormEps = "rms_norm_eps"
        case ropeLocalBaseFreq = "rope_local_base_freq"
        case ropeTheta = "rope_theta"
        case slidingWindow = "sliding_window"
        case torchDtype = "torch_dtype"
        case useCache = "use_cache"
        case vocabSize = "vocab_size"
        case vocabSizePerLayerInput = "vocab_size_per_layer_input"
    }

    // Custom decoder for VLM with nested text_config
    public init(from decoder: Swift.Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        let textContainer = try container.nestedContainer(keyedBy: TextConfigCodingKeys.self, forKey: .textConfig)

        // Decode from text_config
        self.activationSparsityPattern = try textContainer.decodeIfPresent([Float].self, forKey: .activationSparsityPattern)
        self.altupActiveIdx = try textContainer.decodeIfPresent(Int.self, forKey: .altupActiveIdx)
        self.altupCoefClip = try textContainer.decodeIfPresent(Float.self, forKey: .altupCoefClip)
        self.altupCorrectScale = try textContainer.decodeIfPresent(Bool.self, forKey: .altupCorrectScale)
        self.altupLrMultiplier = try textContainer.decodeIfPresent(Float.self, forKey: .altupLrMultiplier)
        self.altupNumInputs = try textContainer.decodeIfPresent(Int.self, forKey: .altupNumInputs)
        self.attentionBias = try textContainer.decode(Bool.self, forKey: .attentionBias)
        self.attentionDropout = try textContainer.decodeIfPresent(Float.self, forKey: .attentionDropout)
        self.finalLogitSoftcapping = try textContainer.decodeIfPresent(Float.self, forKey: .finalLogitSoftcapping)
        self.headDim = try textContainer.decode(Int.self, forKey: .headDim)
        self.hiddenActivation = try textContainer.decodeIfPresent(String.self, forKey: .hiddenActivation)
        self.hiddenSize = try textContainer.decode(Int.self, forKey: .hiddenSize)
        self.hiddenSizePerLayerInput = try textContainer.decodeIfPresent(Int.self, forKey: .hiddenSizePerLayerInput)
        self.initializerRange = try textContainer.decodeIfPresent(Float.self, forKey: .initializerRange)
        self.intermediateSize = try textContainer.decode(Int.self, forKey: .intermediateSize)
        self.laurelRank = try textContainer.decodeIfPresent(Int.self, forKey: .laurelRank)
        self.layerTypes = try textContainer.decodeIfPresent([String].self, forKey: .layerTypes)
        self.maxPositionEmbeddings = try textContainer.decode(Int.self, forKey: .maxPositionEmbeddings)
        self.modelType = try textContainer.decode(String.self, forKey: .modelType)
        self.numAttentionHeads = try textContainer.decode(Int.self, forKey: .numAttentionHeads)
        self.numHiddenLayers = try textContainer.decode(Int.self, forKey: .numHiddenLayers)
        self.numKeyValueHeads = try textContainer.decode(Int.self, forKey: .numKeyValueHeads)
        self.numKvSharedLayers = try textContainer.decodeIfPresent(Int.self, forKey: .numKvSharedLayers)
        self.queryPreAttnScalar = try textContainer.decodeIfPresent(Int.self, forKey: .queryPreAttnScalar)
        self.rmsNormEps = try textContainer.decode(Float.self, forKey: .rmsNormEps)
        self.ropeLocalBaseFreq = try textContainer.decodeIfPresent(Float.self, forKey: .ropeLocalBaseFreq)
        self.ropeTheta = try textContainer.decode(Float.self, forKey: .ropeTheta)
        self.slidingWindow = try textContainer.decode(Int.self, forKey: .slidingWindow)
        self.torchDtype = try textContainer.decodeIfPresent(String.self, forKey: .torchDtype)
        self.useCache = try textContainer.decodeIfPresent(Bool.self, forKey: .useCache)
        self.vocabSize = try textContainer.decode(Int.self, forKey: .vocabSize)
        self.vocabSizePerLayerInput = try textContainer.decodeIfPresent(Int.self, forKey: .vocabSizePerLayerInput)

        // Decode from top level
        self.audioSoftTokensPerImage = try container.decodeIfPresent(Int.self, forKey: .audioSoftTokensPerImage)
        self.audioTokenId = try container.decodeIfPresent(Int.self, forKey: .audioTokenId)
        self.boaTokenId = try container.decodeIfPresent(Int.self, forKey: .boaTokenId)
        self.boiTokenId = try container.decodeIfPresent(Int.self, forKey: .boiTokenId)
        self.eoaTokenId = try container.decodeIfPresent(Int.self, forKey: .eoaTokenId)
        self.eoiTokenId = try container.decodeIfPresent(Int.self, forKey: .eoiTokenId)
        self.eosTokenId = try container.decode([Int].self, forKey: .eosTokenId)
        self.imageTokenId = try container.decodeIfPresent(Int.self, forKey: .imageTokenId)
        self.visionSoftTokensPerImage = try container.decodeIfPresent(Int.self, forKey: .visionSoftTokensPerImage)
    }

}

// MARK: - Helper Functions

/// Apply rotary position embeddings for Gemma3n
private func gemma3nApplyRotaryPosEmb(
    _ q: MLXArray,
    _ k: MLXArray,
    cos: MLXArray,
    sin: MLXArray
) -> (MLXArray, MLXArray) {
    let qEmbed = (q * cos) + (gemma3nRotateHalf(q) * sin)
    let kEmbed = (k * cos) + (gemma3nRotateHalf(k) * sin)
    return (qEmbed, kEmbed)
}

/// Rotate half of the tensor for Gemma3n
private func gemma3nRotateHalf(_ x: MLXArray) -> MLXArray {
    let halfDim = x.dim(-1) / 2
    let x1 = x[.ellipsis, ..<halfDim]
    let x2 = x[.ellipsis, halfDim...]
    return concatenated([-x2, x1], axis: -1)
}

// MARK: - Model Components

// MARK: - Gemma3nAttention

class Gemma3nAttention: Module {
    @ModuleInfo(key: "q_proj") var qProj: Linear
    @ModuleInfo(key: "k_proj") var kProj: Linear
    @ModuleInfo(key: "v_proj") var vProj: Linear
    @ModuleInfo(key: "o_proj") var oProj: Linear

    let numHeads: Int
    let numKVHeads: Int
    let headDim: Int
    let scale: Float

    init(_ config: Gemma3nConfiguration) {
        let hiddenSize = config.hiddenSize
        self.numHeads = config.numAttentionHeads
        self.numKVHeads = config.numKeyValueHeads ?? config.numAttentionHeads
        self.headDim = config.headDim
        self.scale = 1.0 / sqrt(Float(headDim))

        self._qProj.wrappedValue = Linear(hiddenSize, numHeads * headDim, bias: config.attentionBias ?? false)
        self._kProj.wrappedValue = Linear(hiddenSize, numKVHeads * headDim, bias: config.attentionBias ?? false)
        self._vProj.wrappedValue = Linear(hiddenSize, numKVHeads * headDim, bias: config.attentionBias ?? false)
        self._oProj.wrappedValue = Linear(numHeads * headDim, hiddenSize, bias: config.attentionBias ?? false)
    }

    func callAsFunction(
        _ x: MLXArray,
        mask: MLXArray? = nil
    ) -> MLXArray {
        let (B, L, _) = (x.dim(0), x.dim(1), x.dim(2))

        var queries = qProj(x)
        var keys = kProj(x)
        var values = vProj(x)

        // Reshape: [B, L, H, D] -> [B, H, L, D]
        queries = queries.reshaped([B, L, numHeads, headDim]).transposed(0, 2, 1, 3)
        keys = keys.reshaped([B, L, numKVHeads, headDim]).transposed(0, 2, 1, 3)
        values = values.reshaped([B, L, numKVHeads, headDim]).transposed(0, 2, 1, 3)

        // Repeat KV heads if needed (GQA)
        if numKVHeads < numHeads {
            let repeats = numHeads / numKVHeads
            keys = MLXArray.repeated(keys, count: repeats, axis: 1)
            values = MLXArray.repeated(values, count: repeats, axis: 1)
        }

        // Scaled dot-product attention
        var attnWeights = matmul(queries, keys.transposed(0, 1, 3, 2)) * scale

        if let mask = mask {
            attnWeights = attnWeights + mask
        }

        attnWeights = softmax(attnWeights, axis: -1)
        let output = matmul(attnWeights, values)

        // Reshape back: [B, H, L, D] -> [B, L, H*D]
        let outputReshaped = output.transposed(0, 2, 1, 3).reshaped([B, L, numHeads * headDim])

        return oProj(outputReshaped)
    }
}

// MARK: - Gemma3nMLP

class Gemma3nMLP: Module {
    @ModuleInfo(key: "gate_proj") var gateProj: Linear
    @ModuleInfo(key: "up_proj") var upProj: Linear
    @ModuleInfo(key: "down_proj") var downProj: Linear

    init(_ config: Gemma3nConfiguration) {
        let hiddenSize = config.hiddenSize
        let intermediateSize = config.intermediateSize
        self._gateProj.wrappedValue = Linear(hiddenSize, intermediateSize, bias: false)
        self._upProj.wrappedValue = Linear(hiddenSize, intermediateSize, bias: false)
        self._downProj.wrappedValue = Linear(intermediateSize, hiddenSize, bias: false)
    }

    func callAsFunction(_ x: MLXArray) -> MLXArray {
        return downProj(silu(gateProj(x)) * upProj(x))
    }
}

// MARK: - Gemma3nRMSNorm (using built-in RMSNorm)

// Note: Using MLXNN.RMSNorm directly

// MARK: - Gemma3nTransformerBlock

class Gemma3nTransformerBlock: Module {
    @ModuleInfo(key: "self_attn") var attention: Gemma3nAttention
    let mlp: Gemma3nMLP
    @ModuleInfo(key: "input_layernorm") var inputLayerNorm: RMSNorm
    @ModuleInfo(key: "post_attention_layernorm") var postAttentionLayerNorm: RMSNorm

    init(_ config: Gemma3nConfiguration) {
        self._attention.wrappedValue = Gemma3nAttention(config)
        self.mlp = Gemma3nMLP(config)
        self._inputLayerNorm.wrappedValue = RMSNorm(
            dimensions: config.hiddenSize, eps: config.rmsNormEps ?? 1e-6)
        self._postAttentionLayerNorm.wrappedValue = RMSNorm(
            dimensions: config.hiddenSize, eps: config.rmsNormEps ?? 1e-6)
    }

    func callAsFunction(
        _ x: MLXArray,
        mask: MLXArray? = nil
    ) -> MLXArray {
        // Self-attention with residual
        let residual1 = x
        let h1 = inputLayerNorm(x)
        let attnOut = attention(h1, mask: mask)
        let h2 = residual1 + attnOut

        // MLP with residual
        let residual2 = h2
        let h3 = postAttentionLayerNorm(h2)
        let mlpOut = mlp(h3)
        return residual2 + mlpOut
    }
}

// MARK: - Gemma3nModelInner

public class Gemma3nModelInner: Module {
    @ModuleInfo(key: "embed_tokens") var embedTokens: Embedding
    let layers: [Gemma3nTransformerBlock]
    @ModuleInfo(key: "norm") var norm: RMSNorm

    public init(_ config: Gemma3nConfiguration) {
        self._embedTokens.wrappedValue = Embedding(
            embeddingCount: config.vocabSize,
            dimensions: config.hiddenSize
        )
        self.layers = (0..<config.numHiddenLayers).map { _ in
            Gemma3nTransformerBlock(config)
        }
        self._norm.wrappedValue = RMSNorm(
            dimensions: config.hiddenSize, eps: config.rmsNormEps ?? 1e-6)
    }

    public func callAsFunction(_ inputIds: MLXArray) -> MLXArray {
        var h = embedTokens(inputIds)

        for layer in layers {
            h = layer(h, mask: nil)
        }

        return norm(h)
    }
}

// MARK: - Gemma3nModel

public class Gemma3nModel: Module {
    public let vocabularySize: Int
    public let numLayers: Int
    public let numKVHeads: Int

    public let model: Gemma3nModelInner
    @ModuleInfo(key: "lm_head") var lmHead: Linear
    private let config: Gemma3nConfiguration

    public init(_ config: Gemma3nConfiguration) {
        self.config = config
        self.vocabularySize = config.vocabSize
        self.numLayers = config.numHiddenLayers
        self.numKVHeads = config.numKeyValueHeads ?? config.numAttentionHeads
        self.model = Gemma3nModelInner(config)
        self._lmHead.wrappedValue = Linear(config.hiddenSize, config.vocabSize, bias: false)
    }

    /// Embed input tokens
    public func embed(_ inputIds: MLXArray) -> MLXArray {
        return model.embedTokens(inputIds)
    }

    /// Forward pass: compute logits from input token IDs
    public func callAsFunction(_ inputIds: MLXArray) -> MLXArray {
        let h = model(inputIds)
        return lmHead(h)
    }

    /// Sanitize weight keys during model loading
    public func sanitize(weights: [String: MLXArray]) -> [String: MLXArray] {
        // Override in subclass if weight key mapping needed
        return weights
    }
}